### ISSUE TITLE
no load_ddp_controller, load_ddp_discriminator, load_ddp_model

### ISSUE THREAD

**Issue by ZQ8332** [CRazorback/AADG#1]
Hi,

Thank your valuable work. When I run the training code, it is found that there are no load_ddp_controller, load_ddp_discriminator, load_ddp_model in the models folder. Could you share these files?

**Comment by H-CODE6** [comment]
Hello, do you meet TypeError when running code__ init__ () Missing 1 required positional argument: 'classes' This error? We look forward to your help.
