### ISSUE TITLE
__init__() missing 1 required positional argument: 'classes'

### ISSUE THREAD

**Issue by H-CODE6** [CRazorback/AADG#2]
Hello, the author. Recently, we are replicating your paper and experimenting according to the process you disclosed. However, TypeError is always reported during the running process:__ init__ () Missing 1 required positional argument: 'classes', I look forward to your help.

**Comment by ZQ8332** [comment]
hello, i also suffer this problem. have u solved it?

**Comment by H-CODE6** [comment]
Sorry, it hasn't been solved yet. If you can solve this problem, please let me know. Thank you.

**Comment by CRazorback** [comment]
Hello. Sorry for the delay. I have figured out the problem and updated the repo. Please use the new heads.py to replace the one in  segmentation_models_pytorch.

Feel free to ask me any questions if there is a further issue. 😊

**Comment by ZQ8332** [comment]
hi,
thank your letter. but i have used the new HEADS.PY replaced the one in segmentation, but it also had the same error. the detail as below:
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    main()
  File "run.py", line 54, in main
    lanuch_mp_worker(search_worker, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search.py", line 35, in search_worker
    search_seg2d_dg_policy(gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg_2d.py", line 285, in search_seg2d_dg_policy
    model, batch_size, workers = load_ddp_model(ngpus_per_node, args, config)
  File "F:\WORKS\RLretinalseg\AADG-main\models\__init__.py", line 17, in load_ddp_model
    model = smp.DeepLabV3Plus(
  File "F:\py3.8.5\lib\site-packages\segmentation_models_pytorch\deeplabv3\model.py", line 178, in __init__
    self.classification_head = ClassificationHead(
TypeError: __init__() missing 1 required positional argument: 'classes'

**Comment by CRazorback** [comment]
Hi,

Sorry for making a mistake. I have updated the heads.py again and it might work now.

**Comment by H-CODE6** [comment]
Hello, the author. When running the code, when the epoch=30 is reached, the video memory explodes. I find that you will_ EPOCH: 30, can you modify some parameters to ensure successful operation in subsequent rounds? I would like to ask you why this setting does not change the learning rate. Why is it insufficient after 30 rounds of video storage? We look forward to your reply.

**Comment by CRazorback** [comment]
After the warmup epochs, the model will simultaneously conduct reinforcement learning and supervised learning, which requires a larger batch (B x M) to avoid collapse. The model could be trained on the GPU with at least 24GB of video memory  (RTX 3090, A100). You can try to reduce M to make it runnable on your machine. M=2 is minimum but might not have satisfied performance.
