### ISSUE TITLE
 Loading test data from: ./dataset/RVS/STARE is wrong

### ISSUE THREAD

**Issue by jiaqihuang01** [CRazorback/AADG#5]
Hello author, thank you for your excellent paper and code, but when I run 
```python run.py --cfg experiments/rvs_sinkhorn/diversity_ex.yaml --output_dir output/```, 
the following error appears: 
=> creating discriminator 'momentum_feature'
==> Loading train data from: ./dataset/RVS/CHASEDB1/train
==> Loading train data from: ./dataset/RVS/DRIVE/train
==> Loading train data from: ./dataset/RVS/HRF/train
img_num: 50
key STARE has no data
20 images in CHASEDB1
20 images in DRIVE
10 images in HRF
-----Total number of images in train: 50
==> Loading test data from: ./dataset/RVS/STARE
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    main()
  File "run.py", line 54, in main
    lanuch_mp_worker(search_worker, config, args)
  File "/root/autodl-tmp/AADG-main/distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "/root/autodl-tmp/AADG-main/search.py", line 35, in search_worker
    search_seg2d_dg_policy(gpu, ngpus_per_node, config, args)
  File "/root/autodl-tmp/AADG-main/search_dg_2d.py", line 288, in search_seg2d_dg_policy
    train_samplers, train_loader, test_loader = get_seg_dg_dataloader(config, args, batch_size, workers)
  File "/root/autodl-tmp/AADG-main/data/dataloader.py", line 19, in get_seg_dg_dataloader
    testset = RetinalVesselSegmentation(dataroot, phase='test', splitid=cfg.DATASET.DG.TEST, transform=transform_test)
  File "/root/autodl-tmp/AADG-main/data/vessel.py", line 67, in __init__
    self.image_list.append({'image': image_path, 'label': gtPath[idx], 'roi': roiPath[idx]})
IndexError: list index out of range
Could you please advise on how to resolve it?

**Comment by CRazorback** [comment]
Could you kindly check whether image and label paths exist in gtPath[idx] or roiPath[idx]? Please ensure your directory is correctly organized following README.md.

**Comment by jiaqihuang01** [comment]
Thank you for your response. It is indeed missing the roipath for STARE in RVS. I downloaded it from the Google Drive link you provided, and it seems that the ROI file for STARE is missing. Could you please update it? Thank you.

**Comment by CRazorback** [comment]
Hello. The ROI files have been updated.
