### ISSUE TITLE
Calculating dist_12=sinkhorn(domain1_fe,domain2_fe) is wrong

### ISSUE THREAD

**Issue by wwwmj23** [CRazorback/AADG#6]
Hello author, Thanks for your great work and code! But when I run
python run.py --cfg experiments/rvs_sinkhorn/diversity_ex.yaml --output_dir output/,
the following error appears:

Epoch: [59][0/7]	Time 0.605s (0.605s)	Speed 39.7 samples/s	Data 0.492s (0.492s)	Seg Loss 0.24492 (0.24492)	Dis Loss 0.48106 (0.48106)	
Epoch: [59][5/7]	Time 0.083s (0.175s)	Speed 288.7 samples/s	Data 0.000s (0.082s)	Seg Loss 0.26395 (0.25965)	Dis Loss 0.56321 (0.47989)	
Train Epoch 59 time:0.1616 seg loss:0.2602 dis loss:0.4747 dsc@foreground:0.5191
Test Epoch 59 time:0.2243 dsc@foreground:0.7400 acc:0.9387 aucroc:0.9699 sp:0.9785 se:0.6822
=> saving checkpoint to output/rvs/diversity_ex_2023-03-09-22-08
=> best: False
[pyKeOps] Compiling libKeOpstorch18d5d2bc69 in /home/wmj/.cache/pykeops-1.5-cpython-38:
       formula: Max_SumShiftExp_Reduction(( B - (P * ( IntCst(1) - (X | Y) / ( Norm2(X) * Norm2(Y) ) ) ) ),0)
       aliases: X = Vi(0,128); Y = Vj(1,128); B = Vj(2,1); P = Pm(3,1); 
       dtype  : float32
... 
In file included from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/../detail/common.h:258:0,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/../attr.h:13,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/class.h:12,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:13,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/torch/csrc/utils/pybind.h:9,
                 from ./torch_headers.h:19,
                 from <command-line>:0:
/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template/../../version:1:1: error: expected unqualified-id before numeric constant
 1.5
 ^~~
In file included from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/../cast.h:14:0,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/../attr.h:14,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/class.h:12,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:13,
                 from /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/torch/csrc/utils/pybind.h:9,
                 from ./torch_headers.h:19,
                 from <command-line>:0:
/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/pybind11/detail/../detail/descr.h:33:45: error: ‘index_sequence’ has not been declared
     constexpr descr(char const (&s)[N + 1], index_sequence<Is...>) : text{s[Is]..., '\0'} {}
                                             ^~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=2.
make[3]: *** [CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o] Error 1
make[2]: *** [CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/all] Error 2
make[1]: *** [CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/rule] Error 2
make: *** [libKeOps_template_9ffbe9dbe4] Error 2

--------------------- MAKE DEBUG -----------------
Command '['cmake', '--build', '.', '--target', 'libKeOps_template_9ffbe9dbe4', '--', 'VERBOSE=1']' returned non-zero exit status 2.
/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/cmake/data/bin/cmake -S/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template -B/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make  -f CMakeFiles/Makefile2 libKeOps_template_9ffbe9dbe4
make[1]: Entering directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/cmake/data/bin/cmake -S/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template -B/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 --check-build-system CMakeFiles/Makefile.cmake 0
/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/cmake/data/bin/cmake -E cmake_progress_start /home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4/CMakeFiles 2
/usr/bin/make  -f CMakeFiles/Makefile2 CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/all
make[2]: Entering directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
/usr/bin/make  -f CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/build.make CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/depend
make[3]: Entering directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
cd /home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 && /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/cmake/data/bin/cmake -E cmake_depends "Unix Makefiles" /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template /home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 /home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 /home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4/CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
/usr/bin/make  -f CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/build.make CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/build
make[3]: Entering directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
[ 50%] Building CXX object CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o
/usr/bin/c++ -DCUDA_BLOCK_SIZE=192 -DC_CONTIGUOUS=1 -DMAXIDGPU=1 -DMAXTHREADSPERBLOCK0=1024 -DMAXTHREADSPERBLOCK1=1024 -DMODULE_NAME=libKeOps_template_9ffbe9dbe4 -DSHAREDMEMPERBLOCK0=49152 -DSHAREDMEMPERBLOCK1=49152 -DUSE_CUDA=1 -DUSE_DOUBLE=0 -DUSE_HALF=0 -D_FORCE_INLINES -D_GLIBCXX_USE_CXX11_ABI=0 -D__TYPE__=float -DlibKeOps_template_9ffbe9dbe4_EXPORTS -I/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template/../.. -I/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4 -I/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/cmake_scripts/script_template/../../keops -I/usr/local/cuda-11.7/targets/x86_64-linux/include -I/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include -I/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/wmj/anaconda3/envs/pytorch1.13/include/python3.8 -isystem /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/pybind11/include -DUSE_OPENMP -fopenmp -Wall -Wno-unknown-pragmas -fmax-errors=2 -O3 -DNDEBUG -O3 -fPIC -fvisibility=hidden -include torch_headers.h -flto -fno-fat-lto-objects -std=gnu++14 -MD -MT CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o -MF CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o.d -o CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o -c /home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp
CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/build.make:76: recipe for target 'CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.cpp.o' failed
make[3]: Leaving directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/libKeOps_template_9ffbe9dbe4.dir/all' failed
make[2]: Leaving directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
CMakeFiles/
make[1]: Leaving directory '/home/wmj/.cache/pykeops-1.5-cpython-38/build-pybind11_template-libKeOps_template_9ffbe9dbe4'
Makefile:124: recipe for target 'libKeOps_template_9ffbe9dbe4' failed

--------------------- ----------- -----------------
Traceback (most recent call last):
  File "/home/wmj/DG/AADG/run.py", line 71, in <module>
    main()
  File "/home/wmj/DG/AADG/run.py", line 60, in main
    lanuch_mp_worker(search_worker, config, args)
  File "/home/wmj/DG/AADG/distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "/home/wmj/DG/AADG/search.py", line 35, in search_worker
    search_seg2d_dg_policy(gpu, ngpus_per_node, config, args)
  File "/home/wmj/DG/AADG/search_dg_2d.py", line 345, in search_seg2d_dg_policy
    normalized_rewards = train(config, train_loader, model, discriminator, model_criterion,
  File "/home/wmj/DG/AADG/search_dg_2d.py", line 161, in train
    dist_12 = sinkhorn(domain1_fe, domain2_fe)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/samples_loss.py", line 266, in forward
    values = routines[self.loss][backend](
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/sinkhorn_samples.py", line 148, in sinkhorn_online
    a_x, b_y, a_y, b_x = sinkhorn_loop(
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/sinkhorn_divergence.py", line 192, in sinkhorn_loop
    a_x = λ * softmin(ε, C_xx, α_log)  # OT(α,α)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/sinkhorn_samples.py", line 97, in softmin_online
    return -ε * log_conv(x, y, f_y.view(-1, 1), torch.Tensor([1 / ε]).type_as(x)).view(
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 568, in __call__
    out = GenredAutograd.apply(
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 47, in forward
    myconv = LoadKeOps(
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/common/keops_io.py", line 48, in __init__
    self._safe_compile()
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/common/utils.py", line 75, in wrapper_filelock
    func_res = func(*args, **kwargs)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/common/keops_io.py", line 55, in _safe_compile
    compile_generic_routine(
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/pykeops/common/compile_routines.py", line 269, in compile_generic_routine
    fname = list(pathlib.Path(template_build_folder).glob(template_name + "*.so"))[
IndexError: list index out of range
Could you give me some suggestions on how to solve it? Thank you.

**Comment by CRazorback** [comment]
Hello,

Have you made sure that your CUDA, gcc versions are compatible? Otherwise, you will be unable to compile the sinkhorn distance with CUDA and run on GPUs. 

https://www.kernel-operations.io/keops/python/installation.html

Also, it is recommended that you use exactly the same version of softwares as requirement.txt including pytorch (1.8.0) to avoid bugs.

**Comment by wwwmj23** [comment]
> 
Thank you very much for your answer. According to the URL you provided, I have already installed keops, like this
>>> import geomloss
>>> pykeops.clean_pykeops()
[KeOps] /home/wmj/.cache/keops2.1.1/build has been cleaned.
[KeOps] Compiling cuda jit compiler engine ... OK
[pyKeOps] Compiling nvrtc binder for python ... OK  
>>> pykeops.test_numpy_bindings()
[KeOps] Generating code for formula Sum_Reduction((Var(0,3,0)-Var(1,3,1))|(Var(0,3,0)-Var(1,3,1)),1) ... OK
pyKeOps with numpy bindings is working!
>>> pykeops.test_torch_bindings
<function test_torch_bindings at 0x7f97e3c451f0>

But this error occurred during training:
Traceback (most recent call last):
  File "/home/wmj/DG/AADG/run.py", line 71, in <module>
    main()
  File "/home/wmj/DG/AADG/run.py", line 60, in main
    lanuch_mp_worker(search_worker, config, args)
  File "/home/wmj/DG/AADG/distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "/home/wmj/DG/AADG/search.py", line 35, in search_worker
    search_seg2d_dg_policy(gpu, ngpus_per_node, config, args)
  File "/home/wmj/DG/AADG/search_dg_2d.py", line 347, in search_seg2d_dg_policy
    normalized_rewards = train(config, train_loader, model, discriminator, model_criterion,
  File "/home/wmj/DG/AADG/search_dg_2d.py", line 163, in train
    dist_12 = sinkhorn(domain1_fe, domain2_fe)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/samples_loss.py", line 266, in forward
    values = routines[self.loss][backend](
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/sinkhorn_samples.py", line 138, in sinkhorn_online
    softmin_online, log_conv=keops_lse(cost, D, dtype=str(x.dtype)[6:])
  File "/home/wmj/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/geomloss/sinkhorn_samples.py", line 103, in keops_lse
    log_conv = generic_logsumexp(
NameError: name 'generic_logsumexp' is not defined

When I replace 'sinkhorn = SamplesLoss("sinkhorn", cost='( IntCst(1) - (X | Y) / ( Norm2(X) * Norm2(Y) ) )', backend='online')' with 'sinkhorn = SamplesLoss("sinkhorn")', the code can run.

How can I solve this problem? Thank you.

**Comment by CRazorback** [comment]
If you are struggling with the original implementation of sinkhorn distance, you can use 'sinkhorn = SamplesLoss("sinkhorn")' which is actually using Euclidean distance to measure the distance. This implementation is feasible and can achieve similar (almost the same) segmentation performance.

**Comment by wwwmj23** [comment]
Thanks for your reply.! I got it.
