### ISSUE TITLE
Issues related to dataset and code

### ISSUE THREAD

**Issue by wwwmj23** [CRazorback/AADG#7]
Hello author, I am very interested in your paper and code.Thanks for opensourcing the great work. But I found some questions, when comparing label and img. I found that when loading HRF datasets, the label and img did not correspond. The main reason is that the format of  HRF  image is JPG and jpg, resulting in the removal of images in the format JPG during loading,  causing a mismatch between img and label. 
![image](https://user-images.githubusercontent.com/56493902/228119882-d9cc11e4-3e4b-468a-b464-056a5ee8adf7.png)
In addition, I would like to ask why the top ten images are taken during training and the bottom ten images are taken during testing when loading the STARE dataset. Why not take an entire STARE dataset for testing?
![image](https://user-images.githubusercontent.com/56493902/228119938-e6bd49c4-fc1c-4186-a921-5e1ed872428e.png)

**Comment by CRazorback** [comment]
Thank you for your interest.

The JPG issue might be due to different operating systems and environments. I will rename the file in case of such issues.

The STARE training and testing sets are divided in the same way as those in previous works for fair comparison. 

I hope the answer helps.

**Comment by wwwmj23** [comment]
I see. Thank you very much
