### ISSUE TITLE
Regarding the Issue of Data Augmentation

### ISSUE THREAD

**Issue by jiaqihuang01** [CRazorback/AADG#8]
Thank you for your excellent paper and code. I have a few questions about your data augmentation method compared to traditional methods:

- Is it true that no data augmentation method is used within the WARMUP_EPOCH: 60 period, and only the model and discriminator parameters are updated?
- If I set WARMUP_EPOCH=END_EPOCH=300, does it mean there is no effect of data augmentation?
Looking forward to your reply.

**Comment by CRazorback** [comment]
Yes. The training during WARMUP_EPOCH only applies standard and simple data augmentation. If you set WARMUP_EPOCH=END_EPOCH=300, AADG will not take effect.

**Comment by jiaqihuang01** [comment]
Thank you for your response. May I ask what data augmentation techniques are used during the WARMUP_EPOCH period?

**Comment by CRazorback** [comment]
Only random crop is used during warmup stage.
