### ISSUE TITLE
Are the reported results from the best epoch or the last epoch?

### ISSUE THREAD

**Issue by wwwmj23** [CRazorback/AADG#9]
Hi,
Thanks for your great work!

Are the reported results from the mean value of the best epoch or the last epoch for five times? 

In addition, is train.py the baseline？

Thank you.

**Comment by CRazorback** [comment]
The results were reported from the mean value of the best epoch for five times. And train.py is the baseline.

**Comment by wwwmj23** [comment]
> Thank you very much for your prompt reply.
